### ISSUE TITLE
getting unhandled error in events.js

### ISSUE THREAD

**Issue by Geraldf** [kristianmandrup/generator-aurelia-ts#14]
When I run yo aurelia-ts, it creates an error:  

? Ampersand models and collections: Yes
copying /src -> /src
copying /typings -> /typings
copying /styles/sass -> /styles/sass
copying /styles/stylus -> /styles/stylus
events.js:141
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'plugins' of undefined
    at styles (/Users/geraldf/.nvm/versions/io.js/v2.3.4/lib/node_modules/generator-aurelia-ts/generators/styles/write.js:25:86)
    at /Users/geraldf/.nvm/versions/io.js/v2.3.4/lib/node_modules/generator-aurelia-ts/lib/writer.js:12:28
    at Object.writeAll (/Users/geraldf/.nvm/versions/io.js/v2.3.4/lib/node_modules/generator-aurelia-ts/lib/writer.js:19:24)
    at module.exports.yeoman.generators.Base.extend.writing (/Users/geraldf/.nvm/versions/io.js/v2.3.4/lib/node_modules/generator-aurelia-ts/generators/styles/index.js:83:17)
    at /Users/geraldf/.nvm/versions/io.js/v2.3.4/lib/node_modules/generator-aurelia-ts/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback](timers.js:371:17)

**Comment by kristianmandrup** [comment]
Ah, u need to update to the latest release `0.7.3`. I fixed this bug this morning ;)

**Comment by kristianmandrup** [comment]
I do get an error trying to npm install `node-sass` however. Is it due to io.js? 
There are some issues with node-gyp apparently...

https://github.com/Automattic/node-canvas/issues/603#issuecomment-126936553
